### PR TITLE
test.py HasMessage

### PR DESCRIPTION
**Pull request by alextsaihi**

### CODE REVIEW

**Review by jb-adams — CHANGES_REQUESTED** [review]
Please remove all `.DS_Store` files from the PR, and add `.DS_Store` to `.gitignore` so they won't be tracked going forward

**Comment by jb-adams** [comment]
Hi @alextsaihi , in addition to my review comment, can you also set this PR to merge into `develop`? Thanks

**Comment by alextsaihi** [comment]
Hi Jeremy, both of your feedbacks have been done. Let me know if there is anything else I should do.

**Review by jb-adams — APPROVED** [review]

**Comment by jb-adams** [comment]
looks good! merging now

**Pull request merged**
